#!/bin/bash

ln ../../Classes/character.h
ln ../../Classes/character.cpp
ln ../../Classes/condition.h
ln ../../Classes/condition.cpp
ln ../../Classes/helper.h
ln ../../Classes/helper.cpp
ln ../../Classes/item.h
ln ../../Classes/item.cpp
ln ../../Classes/option.h
ln ../../Classes/option.cpp
