#ifndef ZANBARBONEBACKGROUND_H
#define ZANBARBONEBACKGROUND_H

#include "nds.h"

//Code generated by PicToCode version 1.4
//From http://www.richelbilderbeek.nl/ToolPicToCode.htm
struct ZanbarBoneBackground
{
  void Draw(u16 * const buffer,const int x,const int y) const;
  int GetWidth() const { return 256; }
  int GetHeight() const { return 192; }
};


#endif // ZANBARBONEBACKGROUND_H
