#!/bin/bash
for NUMBER in `seq 1 450`
do

  INPUTFILENAME=$NUMBER.txt

  if [ ! -e $INPUTFILENAME ] 
  then 
    continue 
  fi

  OUTPUT_HEADER_FILENAME=$NUMBER.h

  echo "//Autogenerated file" > $OUTPUT_HEADER_FILENAME
  echo "#ifndef GETFILES"$NUMBER"_H" >> $OUTPUT_HEADER_FILENAME
  echo "#define GETFILES"$NUMBER"_H" >> $OUTPUT_HEADER_FILENAME
  echo " " >> $OUTPUT_HEADER_FILENAME
  echo "#include <string>" >> $OUTPUT_HEADER_FILENAME
  echo " " >> $OUTPUT_HEADER_FILENAME
  echo "std::string Get$NUMBER();" >> $OUTPUT_HEADER_FILENAME
  echo " " >> $OUTPUT_HEADER_FILENAME
  echo "#endif //~define GETFILES"$NUMBER"_H" >> $OUTPUT_HEADER_FILENAME

  #echo ".h:\n"
  #cat $OUTPUT_HEADER_FILENAME

  OUTPUT_CPP_FILENAME=$NUMBER.cpp

  echo "#include \"$OUTPUT_HEADER_FILENAME\"" > $OUTPUT_CPP_FILENAME
  echo " " >> $OUTPUT_CPP_FILENAME
  echo "std::string Get$NUMBER()" >> $OUTPUT_CPP_FILENAME
  echo "{" >> $OUTPUT_CPP_FILENAME
  echo "  return" >> $OUTPUT_CPP_FILENAME
  sed 's/.*/    "&\\n"/' $INPUTFILENAME >> $OUTPUT_CPP_FILENAME
  echo "  ;" >> $OUTPUT_CPP_FILENAME
  echo "}" >> $OUTPUT_CPP_FILENAME

done

for BASENAME in About Changelog Hints Introduction Manual Teaser ZanbarBone58 ZanbarBone59 ZanbarBone80
do

  INPUTFILENAME=$BASENAME.txt

  if [ ! -e $INPUTFILENAME ] 
  then 
    echo "ERROR: Could not find$INPUTFILENAME"
    continue 
  fi

  OUTPUT_HEADER_FILENAME=$BASENAME.h

  echo "#include <string>" > $OUTPUT_HEADER_FILENAME
  echo " " >> $OUTPUT_HEADER_FILENAME
  echo "std::string Get$BASENAME();" >> $OUTPUT_HEADER_FILENAME

  #echo ".h:\n"
  #cat $OUTPUT_HEADER_FILENAME

  OUTPUT_CPP_FILENAME=$BASENAME.cpp

  echo "#include \"$OUTPUT_HEADER_FILENAME\"" > $OUTPUT_CPP_FILENAME
  echo " " >> $OUTPUT_CPP_FILENAME
  echo "std::string Get$BASENAME()" >> $OUTPUT_CPP_FILENAME
  echo "{" >> $OUTPUT_CPP_FILENAME
  echo "  return" >> $OUTPUT_CPP_FILENAME
  sed 's/.*/    "&\\n"/' $INPUTFILENAME >> $OUTPUT_CPP_FILENAME
  echo "  ;" >> $OUTPUT_CPP_FILENAME
  echo "}" >> $OUTPUT_CPP_FILENAME

done